<Project Sdk="Microsoft.NET.Sdk">

  

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\_internal\jtp.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>
  <ItemGroup>
  <EmbeddedResource
    Include="Resouces\chrome_supported_domain.txt"
    LogicalName="chrome_supported_domain.txt" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="bin\**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="cookie_test\**\*.cs" />
    <EmbeddedResource Remove="bin\**\*" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="cookie_test\**\*" />
    <None Remove="bin\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="cookie_test\**\*" />
  </ItemGroup>

  <Target Name="RemoveUnusedWebView2WpfReference" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" />
    </ItemGroup>
  </Target>
</Project>
